### PR TITLE
Verifiable PayID validation

### PR DESCRIPTION
**Pull request by rswarthout**
This work introducing the validation of a response that contains verified addresses was completed by @nhartner.

An example response body payload can be found in this ( https://gist.github.com/hbergren/8dd95826dddefc49d8635366031670dd ) gist.

### CODE REVIEW

**Comment by rswarthout** [comment]
Hey @nhartner, I am going to merge this in. I have a few small code formatting changes I am going to make in a subsequent commit, overall this looks great. I appreciate you doing this work. 

Is there anything that I need to work on to add more validation rules for VerifiedAddresses that you are aware of? You did have a TODO in about adding support for other algorithms. Is there a list somewhere that I can reference?

**Comment by 0xCLARITY** [comment]
The full list of supported algorithms for JOSE is listed [here](https://www.iana.org/assignments/jose/jose.xhtml#web-signature-encryption-algorithms), but from skimming through the code, the only important one missing is `ES256K (ECDSA using secp256k1 curve and SHA-256)`.

**Comment by rswarthout** [comment]
Thanks, @hbergren. I did some digging in those packages, and I found that they have that algorithm in an experimental group since the standard is not set. The next release will include this algorithm.

**Comment by rswarthout** [comment]
I just wanted to give @nhartner a heads up that I have updated the object key names based upon the updated gist. Validations against the addresses you provided in Discord are failing since you are returning the old format.

**Pull request merged**
